[package]
name = "folio"
version = "0.2.1"
description = "Folio - Archive.org book downloader and library"
authors = ["Elias Medina"]
edition = "2021"

[lib]
name = "folio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-store = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "cookies", "native-tls", "system-proxy", "stream"] }
scraper = "0.22"
aes = "0.8"
cipher = { version = "0.4", features = ["std"] }
ctr = "0.9"
sha1 = "0.10"
base64 = "0.22"
image = { version = "0.24", default-features = false, features = ["jpeg", "png"] }
printpdf = { version = "0.7", features = ["embedded_images"] }
anyhow = "1"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "migrate"] }
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
tempfile = "3"
regex = "1"
tauri-plugin-updater = "2.10.1"
tauri-plugin-process = "2.3.1"
tauri-plugin-notification = "2.3.3"
futures-util = "0.3.33"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

